# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roxlu/Documents/programming/c++/openni_fork

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roxlu/Documents/programming/c++/openni_fork

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TinyXml

# Build rule for target.
TinyXml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TinyXml
.PHONY : TinyXml

# fast build rule for target.
TinyXml/fast:
	$(MAKE) -f Source/External/TinyXml/CMakeFiles/TinyXml.dir/build.make Source/External/TinyXml/CMakeFiles/TinyXml.dir/build
.PHONY : TinyXml/fast

#=============================================================================
# Target rules for targets named LibJPEG

# Build rule for target.
LibJPEG: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LibJPEG
.PHONY : LibJPEG

# fast build rule for target.
LibJPEG/fast:
	$(MAKE) -f Source/External/LibJPEG/CMakeFiles/LibJPEG.dir/build.make Source/External/LibJPEG/CMakeFiles/LibJPEG.dir/build
.PHONY : LibJPEG/fast

#=============================================================================
# Target rules for targets named OpenNI

# Build rule for target.
OpenNI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenNI
.PHONY : OpenNI

# fast build rule for target.
OpenNI/fast:
	$(MAKE) -f Source/OpenNI/CMakeFiles/OpenNI.dir/build.make Source/OpenNI/CMakeFiles/OpenNI.dir/build
.PHONY : OpenNI/fast

#=============================================================================
# Target rules for targets named OpenNI_PlatformSpecific

# Build rule for target.
OpenNI_PlatformSpecific: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenNI_PlatformSpecific
.PHONY : OpenNI_PlatformSpecific

# fast build rule for target.
OpenNI_PlatformSpecific/fast:
	$(MAKE) -f Source/OpenNI/Linux-x86/CMakeFiles/OpenNI_PlatformSpecific.dir/build.make Source/OpenNI/Linux-x86/CMakeFiles/OpenNI_PlatformSpecific.dir/build
.PHONY : OpenNI_PlatformSpecific/fast

#=============================================================================
# Target rules for targets named nimCodecs

# Build rule for target.
nimCodecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nimCodecs
.PHONY : nimCodecs

# fast build rule for target.
nimCodecs/fast:
	$(MAKE) -f Source/Modules/nimCodecs/CMakeFiles/nimCodecs.dir/build.make Source/Modules/nimCodecs/CMakeFiles/nimCodecs.dir/build
.PHONY : nimCodecs/fast

#=============================================================================
# Target rules for targets named nimMockNodes

# Build rule for target.
nimMockNodes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nimMockNodes
.PHONY : nimMockNodes

# fast build rule for target.
nimMockNodes/fast:
	$(MAKE) -f Source/Modules/nimMockNodes/CMakeFiles/nimMockNodes.dir/build.make Source/Modules/nimMockNodes/CMakeFiles/nimMockNodes.dir/build
.PHONY : nimMockNodes/fast

#=============================================================================
# Target rules for targets named nimRecorder

# Build rule for target.
nimRecorder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nimRecorder
.PHONY : nimRecorder

# fast build rule for target.
nimRecorder/fast:
	$(MAKE) -f Source/Modules/nimRecorder/CMakeFiles/nimRecorder.dir/build.make Source/Modules/nimRecorder/CMakeFiles/nimRecorder.dir/build
.PHONY : nimRecorder/fast

#=============================================================================
# Target rules for targets named Sample-NiAudioSample

# Build rule for target.
Sample-NiAudioSample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample-NiAudioSample
.PHONY : Sample-NiAudioSample

# fast build rule for target.
Sample-NiAudioSample/fast:
	$(MAKE) -f Samples/NiAudioSample/CMakeFiles/Sample-NiAudioSample.dir/build.make Samples/NiAudioSample/CMakeFiles/Sample-NiAudioSample.dir/build
.PHONY : Sample-NiAudioSample/fast

#=============================================================================
# Target rules for targets named Sample-NiSimpleViewer

# Build rule for target.
Sample-NiSimpleViewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample-NiSimpleViewer
.PHONY : Sample-NiSimpleViewer

# fast build rule for target.
Sample-NiSimpleViewer/fast:
	$(MAKE) -f Samples/NiSimpleViewer/CMakeFiles/Sample-NiSimpleViewer.dir/build.make Samples/NiSimpleViewer/CMakeFiles/Sample-NiSimpleViewer.dir/build
.PHONY : Sample-NiSimpleViewer/fast

#=============================================================================
# Target rules for targets named Sample-NiConvertXToONI

# Build rule for target.
Sample-NiConvertXToONI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sample-NiConvertXToONI
.PHONY : Sample-NiConvertXToONI

# fast build rule for target.
Sample-NiConvertXToONI/fast:
	$(MAKE) -f Samples/NiConvertXToONI/CMakeFiles/Sample-NiConvertXToONI.dir/build.make Samples/NiConvertXToONI/CMakeFiles/Sample-NiConvertXToONI.dir/build
.PHONY : Sample-NiConvertXToONI/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... TinyXml"
	@echo "... LibJPEG"
	@echo "... OpenNI"
	@echo "... OpenNI_PlatformSpecific"
	@echo "... nimCodecs"
	@echo "... nimMockNodes"
	@echo "... nimRecorder"
	@echo "... Sample-NiAudioSample"
	@echo "... Sample-NiSimpleViewer"
	@echo "... Sample-NiConvertXToONI"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

