# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/roxlu/Documents/programming/c++/openni_fork

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/roxlu/Documents/programming/c++/openni_fork

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/roxlu/Documents/programming/c++/openni_fork/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyxml

# Build rule for target.
tinyxml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml
.PHONY : tinyxml

# fast build rule for target.
tinyxml/fast:
	$(MAKE) -f Source/External/TinyXml/CMakeFiles/tinyxml.dir/build.make Source/External/TinyXml/CMakeFiles/tinyxml.dir/build
.PHONY : tinyxml/fast

#=============================================================================
# Target rules for targets named jpeg

# Build rule for target.
jpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jpeg
.PHONY : jpeg

# fast build rule for target.
jpeg/fast:
	$(MAKE) -f Source/External/LibJPEG/CMakeFiles/jpeg.dir/build.make Source/External/LibJPEG/CMakeFiles/jpeg.dir/build
.PHONY : jpeg/fast

#=============================================================================
# Target rules for targets named openni

# Build rule for target.
openni: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni
.PHONY : openni

# fast build rule for target.
openni/fast:
	$(MAKE) -f Source/OpenNI/CMakeFiles/openni.dir/build.make Source/OpenNI/CMakeFiles/openni.dir/build
.PHONY : openni/fast

#=============================================================================
# Target rules for targets named openni_linux

# Build rule for target.
openni_linux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_linux
.PHONY : openni_linux

# fast build rule for target.
openni_linux/fast:
	$(MAKE) -f Source/OpenNI/Linux-x86/CMakeFiles/openni_linux.dir/build.make Source/OpenNI/Linux-x86/CMakeFiles/openni_linux.dir/build
.PHONY : openni_linux/fast

#=============================================================================
# Target rules for targets named openni_modules_nimcodecs

# Build rule for target.
openni_modules_nimcodecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_modules_nimcodecs
.PHONY : openni_modules_nimcodecs

# fast build rule for target.
openni_modules_nimcodecs/fast:
	$(MAKE) -f Source/Modules/nimCodecs/CMakeFiles/openni_modules_nimcodecs.dir/build.make Source/Modules/nimCodecs/CMakeFiles/openni_modules_nimcodecs.dir/build
.PHONY : openni_modules_nimcodecs/fast

#=============================================================================
# Target rules for targets named openni_modules_nimmocknodes

# Build rule for target.
openni_modules_nimmocknodes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_modules_nimmocknodes
.PHONY : openni_modules_nimmocknodes

# fast build rule for target.
openni_modules_nimmocknodes/fast:
	$(MAKE) -f Source/Modules/nimMockNodes/CMakeFiles/openni_modules_nimmocknodes.dir/build.make Source/Modules/nimMockNodes/CMakeFiles/openni_modules_nimmocknodes.dir/build
.PHONY : openni_modules_nimmocknodes/fast

#=============================================================================
# Target rules for targets named openni_modules_nimrecorder

# Build rule for target.
openni_modules_nimrecorder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_modules_nimrecorder
.PHONY : openni_modules_nimrecorder

# fast build rule for target.
openni_modules_nimrecorder/fast:
	$(MAKE) -f Source/Modules/nimRecorder/CMakeFiles/openni_modules_nimrecorder.dir/build.make Source/Modules/nimRecorder/CMakeFiles/openni_modules_nimrecorder.dir/build
.PHONY : openni_modules_nimrecorder/fast

#=============================================================================
# Target rules for targets named openni_sample_niaudiosample

# Build rule for target.
openni_sample_niaudiosample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_sample_niaudiosample
.PHONY : openni_sample_niaudiosample

# fast build rule for target.
openni_sample_niaudiosample/fast:
	$(MAKE) -f Samples/NiAudioSample/CMakeFiles/openni_sample_niaudiosample.dir/build.make Samples/NiAudioSample/CMakeFiles/openni_sample_niaudiosample.dir/build
.PHONY : openni_sample_niaudiosample/fast

#=============================================================================
# Target rules for targets named openni_sample_nisimpleviewer

# Build rule for target.
openni_sample_nisimpleviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 openni_sample_nisimpleviewer
.PHONY : openni_sample_nisimpleviewer

# fast build rule for target.
openni_sample_nisimpleviewer/fast:
	$(MAKE) -f Samples/NiSimpleViewer/CMakeFiles/openni_sample_nisimpleviewer.dir/build.make Samples/NiSimpleViewer/CMakeFiles/openni_sample_nisimpleviewer.dir/build
.PHONY : openni_sample_nisimpleviewer/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tinyxml"
	@echo "... jpeg"
	@echo "... openni"
	@echo "... openni_linux"
	@echo "... openni_modules_nimcodecs"
	@echo "... openni_modules_nimmocknodes"
	@echo "... openni_modules_nimrecorder"
	@echo "... openni_sample_niaudiosample"
	@echo "... openni_sample_nisimpleviewer"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

